name = (input("Enter your Name: "))
age = (input("Enter your Age: "))
occupation = (input("Enter your Occupation: "))
university_name = (input("Enter your Univerity Name"))
university_address = (input("Enter your university Address: "))
address = (input("Enter your Address: "))
number = (input("Enter your number: "))
fathers_name = (input("Enter your Fathers Name: "))
fathers_occupation = (input("Enter your Fathers Occupation: "))
mothers_name = (input("Enter your Mothers Name: "))
mothers_occupation = (input("Enter your Mothers Occupation: "))

print(name)
print(age)
print(occupation)
print(university_name)
print(university_address)
print(address)
print(number)
print(fathers_name)
print(fathers_occupation)
print(mothers_name)
print(fathers_occupation)
